name: dlsp
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch==2.0.1
  - torchaudio==2.0.2
  - pip
  - pip:
    - torchmetrics
    - mne
    - pandas
    - matplotlib
    - scikit-learn
    - scipy
    - wandb
    - ipykernel
    - tqdm